---
all:
  hosts:
  ## add manual entries here
  children:
    master:
      hosts:
        postgres1:
          ansible_host: 192.168.122.165
    standby:
      hosts:
        postgres2:
          ansible_host: 192.168.122.58