---
# tasks file for master
- name: Install Postgresql packages
  ansible.builtin.dnf:
    name: postgresql-server, postgresql-contrib, postgresql
    state: present

- name: Create the postgresql installation folder
  ansible.builtin.file:
    path: "{{ data_disk_path + postgresql_path }}"
    state: directory
    mode: "0755"
    owner: postgres
    group: root

- name: Check whether postgresql is already installed in the target path.
  ansible.builtin.stat:
    path: "{{ data_disk_path + postgreql_root + postgresql_path }}/pg_hba.conf"
  register: postgres_data

- name: Initialise PostgreSQL if not already installed
  tags: postgres_initdb
  ansible.builtin.command:
    cmd: sudo su --command 'pg_ctl initdb --pgdata={{ data_disk_path + postgresql_root + postgresql_path }}' --login postgres
  when: not postgres_data.stat.exists

- name: Set selinux postgresql permissions on postgresql root folder
  ansible.builtin.command:
    cmd: sudo chcon -Rt postgresql_db_t {{ data_disk_path + postgresql_root }}

- name: Install service file for postgresql
  ansible.builtin.copy:
    src: files/postgresql-13.service
    dest: /etc/systemd/system/postgresql-13.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable and start postgresql
  ansible.builtin.systemd_service:
    name: postgresql-13
    state: started
    enabled: true
    masked: false

- name: Secure the postgresql installation
  block:

    - name: Set password encryption to SCRAM-SHA-256
      ansible.builtin.lineinfile:
        path: "{{ data_disk_path + postgresql_root + postgresql_path }}/postgresql.conf"
        regex: password_encryption = scram-sha-256
